# Generated by Django 5.2.7 on 2025-11-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categqoria',
            new_name='categoria',
        ),
    ]
