# Generated by Django 5.2.7 on 2025-11-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_categqoria_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quanttidade',
            new_name='quantidade',
        ),
    ]
