# Generated by Django 5.2.7 on 2025-11-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_quanttidade_produto_quantidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='ProdutoModel',
        ),
    ]
