# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_produto_produtomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
