# Generated by Django 5.2.7 on 2025-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produtomodel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('bebida', 'Bebida'), ('higiene', 'Higiene'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
