# Generated by Django 5.2.8 on 2025-11-10 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_produtomodel_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
